### ISSUE TITLE
Does 10.8 have the same bug in IOKit?

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#18] opened 2013-11-08 11:59 UTC

**Comment by adcxyz** [comment] 2015-05-20 04:29
is this still the same in 10.10? 
is there a simple reproducer that does work on linux and fail on OSX?

**Comment by adcxyz** [comment] 2015-05-28 18:08
I think Marije had that solved in Copenhagen;
is there an example yet that works on OSX?
if not, please commit one.

**Comment by LFSaw** [comment] 2015-05-29 19:02
@sensestage ?

**Comment by adcxyz** [comment] 2015-06-15 08:27
pretty please ;-) ?

**Comment by LFSaw** [comment] 2015-06-21 10:16
I'll meet her tomorrow and will not let her go until she answers... ;-)

**Comment by adcxyz** [comment] 2015-09-04 19:32
is this bug still present or is it solved/solvable now?

**Comment by LFSaw** [comment] 2015-10-16 20:53
@sensestage ??

**Comment by sensestage** [comment] 2015-10-17 11:04
It can be tested with the Ferrari Gamepad - the rumble outputs.
I cannot fix it on OSX, it is deeper down in the Apple HID drivers. We need
to bug Apple about it...

**Comment by bhabbestad** [comment] 2015-10-17 11:59
> We need to bug Apple about it…

who has got the best way in?

b


> 
> 
>

**Comment by adcxyz** [comment] 2015-10-17 12:50
Apologies, but I still have no idea - What exactly is "the same bug" please? 

Some reverse guessing : 
* On OSX, HID does not report all the elements properly - Y/N?
* It is always only HID output elements that are concerned - or others too? 
* On the Ferrari gamepad ("thrustmaster-run-n-drive" and -wireless), the bug shows - 
** there should be two rumble output elements, but there is only one? or none?

Other HID descs that should have outputs: 
* saitek-impact-gamepad - 4 leds, commented out
* shanwan-wirelessgamepad - 5 outs, one modeOut, 4 rumbles
* JessTech dual analog rumble - none in the desc, but given the name, one would expect rumble outs?

I can test the Ferrari and the Saitek Impact gamepads, but what is the relevant test code?
Who has a Shanwan and a JessTech, and can test?

**Comment by sensestage** [comment] 2015-10-17 13:07
With the Ferrari, there should be two rumble outputs; on OSX two are
reported, but one is wrongly reported and therefor cannot be used. This is
a bug in the HID descriptor parser that is happening in the OSX closed
source backend.
I don't know if the other HID's are also affected.

Testing it is as simple as:
opening the device, create a description (HID descriptor is automatically
parsed), and see if you can send output data to the output element, and
something happens, as you would expect.

Code should be something like this:
k.elementAt( \rumble, \l ).value_(0);
k.elementAt( \rumble, \l ).value_(255);

**Comment by adcxyz** [comment] 2015-10-17 13:40
// ok thanks - more detailed tests: 
```
k = MKtl(\k, "*drive");
// should turn vibration on/off and does nothing ATM:
k.elementAt( \rumble, \l ).value_(0); 
k.elementAt( \rumble, \l ).value_(255);
k.elementAt( \rumble, \r ).value_(0);
k.elementAt( \rumble, \r ).value_(255);

// talk to the HID directly:
x = k.device.source;
x = HID.openDevices[0];

// test which ones are rumbles
fork { 
	x.elements.do { |elem| 
		elem.postln.value_(255);
		1.wait;
		elem.postln.value_(0);
	}
};
// rumble left, lower freq
x.elements[32].value = 255;
x.elements[32].value = 0;
// rumble right, higher freq, less intense
x.elements[33].value = 255;
x.elements[33].value = 0;

The elements report as: 
-> a HIDElement(id: 32, type: 2, usage: 187, uPage: 1)
-> a HIDElement(id: 33, type: 2, usage: 187, uPage: 1)

So we do need to distinguish by id even when usage and usagePage are present, yes?

```

**Comment by sensestage** [comment] 2016-03-21 08:43
Reading the discussion, I don't see how this would then solve it:

```
(
			key: 'rumble',
			shared: ('elementType': 'rumble', 'ioType': 'out',
				spec: \lin255, mode: \minimum),
			elements: [
				(
					key: \l,
					'hidUsage': 187, 'hidUsagePage': 1, hidElementID: 32,
					'style': (row: 4, column: 0, showLabel: true)
				),
				(
					key: \r,
					'hidUsage': 0, 'hidUsagePage': 1, hidElementID: 32,
					'style': (row: 4, column: 5, showLabel: true)
				)
			]
		)
```

**Comment by sensestage** [comment] 2016-03-21 08:45
Also: do you feel it rumbling on the right side?
On Linux I feel distinct differences between the left and the right side rumbling.

**Comment by adcxyz** [comment] 2016-03-21 14:13
just tested this again - there seems to be only general rumble, 
and both rumble outputs set the same motor intensity.

I also tried setting hidUsage to (nonsense value) 123, and it still sets the same motor. 

I put it as notes in the desc file for the future.

// test for rumble outputs
f.elAt( \rumble, \l ).value_(1);
f.elAt( \rumble, \l ).value_(0.5);
f.elAt( \rumble, \l ).value_(0);

f.elAt( \rumble, \r ).value_(1);
f.elAt( \rumble, \r ).value_(0.5);
f.elAt( \rumble, \r ).value_(0);

**Comment by sensestage** [comment] 2016-03-21 23:22
And with the direct HID interface, can you distinguish between the two?

**Comment by sensestage** [comment] 2016-03-21 23:23
If so - I would say that we leave a note in the descriptor that one of the rumbles doesn't work for OSX.

**Comment by adcxyz** [comment] 2016-03-22 10:32
yes they are two distinct devices.

**Comment by adcxyz** [comment] 2016-03-22 10:35
already there in thrustmaster-run-n-drive-wireless.desc.scd:

Notes:
* rumble does nothing on wireless, works on wired.

and in  thrustmaster-run-n-drive.desc.scd:

Notes:

* rumble is only on a single motor, no left and right ( see test below)


good enough?

**Comment by LFSaw** [comment] 2016-03-22 11:31
> Notes:
> * rumble does nothing on wireless, works on wired.
> 
> and in thrustmaster-run-n-drive.desc.scd:
> 
> Notes:
> 
> * rumble is only on a single motor, no left and right ( see test below)
> 


i.e. they are part of the machine-readable description. please do not duplicate that information into comments (hard to spot if things change...)


cheers
	Till

**Comment by adcxyz** [comment] 2016-03-22 13:41
> On 22/03/2016, at 12:31 , LFSaw <notifications@github.com> wrote:
> 
> > Notes:
> > * rumble does nothing on wireless, works on wired.
> > 
> > and in thrustmaster-run-n-drive.desc.scd:
> > 
> > Notes:
> > 
> > * rumble is only on a single motor, no left and right ( see test below)
> > 
> 
> 
> i.e. they are part of the machine-readable description. please do not duplicate that information into comments (hard to spot if things change…)

They were just in commented-out text at the top of the file. 
Are you proposing to put all comments into the compiled part of the desc? 

I thought so far that : 

deviceInfo: (
	notes: “should be short for some reason. ”
);

should we include everything now in comments on top there? 
and everything that is code examples in testCode?
or maybe testCode just what is needed for verification, 
and exampleCode for everything else?

best a

**Comment by sensestage** [comment] 2016-03-25 10:44
Note that the rumble does work on both sides on Linux, it is an OSX specific issue. At least in the wired version. I don't have a wireless one to test.

**Comment by adcxyz** [comment] 2017-07-06 18:47
has been stuck for 15 months ... closing.

**Closed by adcxyz** 2017-07-06 18:47 UTC
Labels: HIDMKtl, osx, question
