### ISSUE TITLE
confusion between run'n'drive and wireless run'n'drive

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#167] opened 2015-05-19 10:30 UTC

**Comment by adcxyz** [comment] 2015-06-01 07:56
looked at this, with both devices attached, and the underlying problem is

the shortname is the same for both (as for others, e.g. the Steinberg CMC things), 
so just calling MKtl('rnnd0') can really be either of the two descriptions. 
this touches issues #188, #168, #209 (and maybe #185)

possible solutions I see: (#188)
1. keep the shortname as is, 
    and if there are multiple matches, and check by actual idInfo reported
    -> should work works for HID and MIDI, not for virtual devices or OSC
2. for non-unique shortnames, require filename and prefer filename for device ID
    -> would be systematic and clear, maybe a bit cumbersome
3. change the shortname algorithm so the ones for known devices become unique
    -> would work now, new devices might clash again
4. use full idInfo in shortname 
    -> ugly, and as is #209 still not unique for MIDI devices which register multiply  
    under the same name and Port 1, Port 2, Port 3 (e.g. the QuNexus)

I would propose that option 2 should be made to work, (unique filename 
   should win over nonunique shortname), 
and 3, shortname algorithm should create unique names
and to solve #209, use solution proposed there.

**Comment by LFSaw** [comment] 2015-06-01 20:20
this is a duplicate of #210

**Closed by LFSaw** 2015-06-01 20:20 UTC
Labels: hardware specific
